"""add_morador_id

Revision ID: 6470a796a404
Revises: aa3215c6e136
Create Date: 2026-05-22 12:20:06.560654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6470a796a404'
down_revision: Union[str, None] = 'aa3215c6e136'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('morador_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'morador_id')
    # ### end Alembic commands ###
