"""initial_migration

Revision ID: aa3215c6e136
Revises: None
Create Date: 2026-05-22 02:55:34.581444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa3215c6e136'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispositivos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('ip', sa.String(length=50), nullable=False),
    sa.Column('porta', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('localizacao', sa.String(length=100), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('ultimo_contacto', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('funcionarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('bi', sa.String(length=15), nullable=False),
    sa.Column('nif', sa.String(length=15), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('genero', sa.String(length=10), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('endereco', sa.String(length=255), nullable=False),
    sa.Column('cargo', sa.String(length=100), nullable=False),
    sa.Column('departamento', sa.String(length=100), nullable=False),
    sa.Column('data_admissao', sa.Date(), nullable=False),
    sa.Column('biometria_template', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funcionarios_bi'), 'funcionarios', ['bi'], unique=True)
    op.create_index(op.f('ix_funcionarios_email'), 'funcionarios', ['email'], unique=True)
    op.create_index(op.f('ix_funcionarios_nif'), 'funcionarios', ['nif'], unique=True)
    op.create_table('horarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('hora_entrada', sa.Time(), nullable=False),
    sa.Column('hora_saida', sa.Time(), nullable=False),
    sa.Column('tolerancia', sa.Integer(), nullable=False),
    sa.Column('horas_diarias', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('dias_semana', sa.String(length=100), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assiduidade',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('entrada', sa.Time(), nullable=True),
    sa.Column('saida', sa.Time(), nullable=True),
    sa.Column('horas_trabalhadas', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('horas_extras', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('dispositivo_entrada_id', sa.Integer(), nullable=True),
    sa.Column('dispositivo_saida_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assiduidade_data'), 'assiduidade', ['data'], unique=False)
    op.create_table('ausencias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('justificada', sa.Boolean(), nullable=False),
    sa.Column('documento_comprovativo', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('observacoes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contratos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('salario_base', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subsidio_alimentacao', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subsidio_transporte', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('outros_subsidios', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ferias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('dias_gozados', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('observacoes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'ADMIN_RH', 'GESTOR', 'PORTEIRO', 'FUNCIONARIO', name='roleenum'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=True),
    sa.Column('morador_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('acao', sa.String(length=50), nullable=False),
    sa.Column('modulo', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificacoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('lida', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('salarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('salario_base', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subsidio_alimentacao', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subsidio_transporte', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('outros_subsidios', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('bonus', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('seguranca_social_func', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('seguranca_social_emp', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('irt', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('faltas_deducao', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('outras_deducoes', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('salario_bruto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('salario_liquido', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('processado_por', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['processado_por'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('salarios')
    op.drop_table('notificacoes')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('ferias')
    op.drop_table('contratos')
    op.drop_table('ausencias')
    op.drop_index(op.f('ix_assiduidade_data'), table_name='assiduidade')
    op.drop_table('assiduidade')
    op.drop_table('horarios')
    op.drop_index(op.f('ix_funcionarios_nif'), table_name='funcionarios')
    op.drop_index(op.f('ix_funcionarios_email'), table_name='funcionarios')
    op.drop_index(op.f('ix_funcionarios_bi'), table_name='funcionarios')
    op.drop_table('funcionarios')
    op.drop_table('dispositivos')
    # ### end Alembic commands ###
